#!/bin/bash


TARGETS_LIST=(all essential)
TARGETS_ALL=(hyprland hyprlock hyprpaper nvim tmux waybar wezterm)
TARGETS_ESSENTIAL=(nvim tmux)

SYMLINK=true
DRY_RUN=false


function help {
    echo "Install script for dotfiles."
    echo "Usage: `basename $0` <OPTIONS> <TARGET>"
}

function options {
    echo "Options:"
    echo "  -h, --help         Show this help message"
    echo "  -ns, --no-symlink  Do not create symlinks, just copy files"
    echo "  --dry-run          Do not commit changes, just show what would be done"
}

function targets {
    echo "Targets:"
    echo "  all, -a            Install all dotfiles"
    echo "  essential, -e      Install essential dotfiles only"
    echo "  <file>             Install a specific dotfile"
}


if [[ $# -lt 1 ]]; then
    help
    exit 1
fi

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            help
            echo ""
            options
            echo ""
            targets
            exit 1
            ;;
        -ns|--no-symlink)
            SYMLINK=false
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        *)
            if [[ -n ${TARGET} ]]; then
                echo "Error: Multiple targets specified."
                exit 1
            fi
            case $1 in
                all|-a)
                    TARGET="all"
                    TARGETS=("${TARGETS_ALL[@]}")
                    ;;
                essential|-e)
                    TARGET="essential"
                    TARGETS=("${TARGETS_ESSENTIAL[@]}")
                    ;;
                *)
                    TARGET=$1
                    TARGETS=($1)
                    ;;
            esac
            shift
            ;;
    esac
done

if [[ -z ${TARGET} ]]; then
    echo "Error: No target specified."
    exit 1
fi

if [[ ! " ${TARGETS_LIST[@]} " =~ " ${TARGET} " ]] && [[ ! " ${TARGETS_ALL[@]} " =~ " ${TARGET} " ]]; then
    echo "Error: Invalid target specified."
    targets
    exit 1
fi


echo "Installing ${TARGET}:"
echo "- Targets: ${TARGETS[@]}"
echo "- Using symlinks: ${SYMLINK}"

if [[ ${DRY_RUN} == true ]]; then
    echo "- Dry run: ${DRY_RUN}"
    exit 0
fi

echo -ne "Continue? [Y/n] "
read -r CONTINUE
if [[ ! ${CONTINUE} =~ ^[Yy]$ ]] && [[ -n ${CONTINUE} ]]; then
    echo "Aborting."
    exit 1
fi

COMMAND=""
if [[ ${SYMLINK} == true ]]; then
    echo "Creating symlinks..."
    COMMAND="ln -s"
else
    echo "Copying files..."
    COMMAND="cp -r"
fi

for DOTFILE in "${TARGETS[@]}"; do
    echo -ne "- ${DOTFILE}: "
    SOURCE="${HOME}/.dotfiles/${DOTFILE}"
    ${COMMAND} ${SOURCE} ${HOME} && echo "Success!" || echo "Failed..."
done
